name: cmake-build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    name: vcpkg (${{matrix.os}})
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
          name: ubuntu
          nuget: mono `vcpkg fetch nuget | tail -n 1`
        - os: macos-15
          name: macos
          nuget: mono `vcpkg fetch nuget | tail -n 1`
        - os: windows-2022
          name: windows
          nuget: nuget
    runs-on: ${{ matrix.os }}
    permissions:
      packages: write
      contents: read
    env:
      VCPKG_COMMIT: ce613c41372b23b1f51333815feb3edd87ef8a8b # 2025.04.09
      NUGET_FEED_URL: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'
        persist-credentials: false

    - name: Install ninja-build tool
      if: matrix.name == 'ubuntu'
      uses: seanmiddleditch/gha-setup-ninja@v6
      
    - name: Unzip IDA SDK
      shell: bash
      env:
        IDASDK_SECRET: ${{ secrets.IDASDK_SECRET }}
      if: env.IDASDK_SECRET != ''
      run: |
        mkdir -p build
        ./.github/scripts/decrypt_secret.sh
        unzip -q build/idasdk_teams82.zip \
              -d build/

    - name: Enable Developer Command Prompt (Windows)
      if: matrix.name == 'windows'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: Setup vcpkg environment
      shell: bash
      run: |
        git -C "$VCPKG_INSTALLATION_ROOT" fetch --all
        git -C "$VCPKG_INSTALLATION_ROOT" reset --hard ${{ env.VCPKG_COMMIT }}
        "$VCPKG_INSTALLATION_ROOT/bootstrap-vcpkg.sh"

        if [[ "${{ matrix.name }}" == "macos" ]]; then
          brew install mono
        elif [[ "${{ matrix.name }}" == "ubuntu" ]]; then
          sudo apt-get install --yes mono-complete
        fi

        ${{ matrix.nuget }} \
          sources add \
          -Source "${{ env.NUGET_FEED_URL }}" \
          -StorePasswordInClearText \
          -Name GitHubPackages \
          -UserName "${{ github.repository_owner }}" \
          -Password "${{ secrets.GITHUB_TOKEN }}"
        ${{ matrix.nuget }} \
          setapikey "${{ secrets.GITHUB_TOKEN }}" \
          -Source "${{ env.NUGET_FEED_URL }}"

    - name: Configure CMake
      env:
        VCPKG_ROOT: ${{env.VCPKG_INSTALLATION_ROOT}}
        VCPKG_BINARY_SOURCES: clear;nuget,${{ env.NUGET_FEED_URL }},readwrite
      run: cmake --preset ci-${{matrix.name}}-vcpkg
          -DBINEXPORT_ENABLE_IDAPRO=${{ secrets.IDASDK_SECRET != '' && 'ON' || 'OFF'}}
          -DIdaSdk_ROOT_DIR=build/idasdk_teams82

    - name: Build
      run: cmake --build --preset ci-${{matrix.name}}-vcpkg

    - name: Test
      run: ctest --preset ci-${{matrix.name}}-vcpkg -R '^[A-Z]'

    - name: Install
      run: cmake --build --preset ci-${{matrix.name}}-vcpkg --target install

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4.6.2
      with:
        name: BinExport-${{ runner.os }}-${{ runner.arch }}
        path: |
          build/ci-${{matrix.name}}-vcpkg/install/
